[package]
name = "game"

version.workspace = true
license.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true

[[bin]]
name = "game"
path = "src/bin/main.rs"

[dependencies]
kernel = { path = "../kernel" }
