[package]
name = "lib-kernel"
description = "(Summer) Library to support kernels"

version.workspace = true
license.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true

[lib]
name = "lib_kernel"
path = "src/lib.rs"
crate-type = [
    "rlib"
]
